
services:
  frontend:
    image: 1nfosecsingh/frontend:dev-latest
    container_name: frontend
    networks:
      - app 
  
  backend:
    image: 1nfosecsingh/backend:dev-latest
    container_name: backend
    depends_on:
      - frontend
    networks:
      - app 

  notification:
    image: 1nfosecsingh/notification:dev-latest
    container_name: notification
    depends_on:
      - frontend
    networks:
      - app 

  gateway:
    image: 1nfosecsingh/gateway:dev-latest
    container_name: gateway
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - notification
    networks:
      - app 
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    depends_on:
      - frontend
      - backend
      - notification
      - gateway
    networks:
      - app 
    volumes:
      - ../monitoring-setup/prometheus-config.yaml:/etc/prometheus/prometheus.yml
  


networks:
  app:

