name: dev cd pipeline

#run when ci pipeline completed. 
on:
  workflow_run:
    workflows: ["dev ci pipeline"]
    type:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        run: echo "Test working fine"

  
